import Head from 'next/head'
import Footer from '@/companes/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Donate-cripito</title>
        <meta charSet= 'utf-8' />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <div className='container px-4 py-5'>
        <div className="row flex-lg-row-reverse align-items-center py-5 g-5">
          <div className='col-10 col-sm-8 col-lg-6'>
            <img src="https://images.unsplash.com/photo-1520694478166-daaaaec95b69?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80" className="d-blok mx-lg-auto img-fluid" width="700" height="500"></img>
          </div>
          <div className="col-lg-6">
             <h1 className="display-5 fw-bold text-body-emphasis lh-1 mb-3">teste</h1>
             <p className="lead">Sua plataforma decentralizada de doaçoes </p>
             <p className="lead mb-3"> Autetique sua carteira, ou doe para para uma campanha existete</p>
             <div>
               <buttom type="button" className='btn btn-primary btn-lg px-4 me-md-2'>
                <img src="/metamask.svg" width="64" className="me-3"></img> 
                conectar com a MetaMask             
               </buttom>
             </div>
          </div>
        </div>

        <Footer/>
        
      </div>
      
   </> 
  )
}
